export interface SurahList {
  id: number;
  name: string;
  arabicName: string;
  ayat: number;
}

export const surahList: SurahList[] = [
  {
    id: 1,
    name: 'Al-Fatihah',
    arabicName: 'الفاتحة',
    ayat: 10,
  },
  {
    id: 2,
    name: 'Al-Baqarah',
    arabicName: 'البقرة',
    ayat: 286,
  },
  {
    id: 3,
    name: "Ali 'Imran",
    arabicName: 'الآية',
    ayat: 200,
  },
  {
    id: 4,
    name: "An-Nisa'",
    arabicName: 'النساء',
    ayat: 176,
  },
  {
    id: 5,
    name: "Al-Ma'idah",
    arabicName: 'المائدة',
    ayat: 120,
  },
  {
    id: 6,
    name: "Al-An'am",
    arabicName: 'النور',
    ayat: 165,
  },
  {
    id: 7,
    name: "Al-A'raf",
    arabicName: 'العفو',
    ayat: 206,
  },
  {
    id: 8,
    name: 'Al-Anfal',
    arabicName: 'الغاشية',
    ayat: 75,
  },
  {
    id: 9,
    name: 'At-Taubah',
    arabicName: 'التوبة',
    ayat: 129,
  },
  {
    id: 10,
    name: 'Yunus',
    arabicName: 'يونس',
    ayat: 109,
  },
  {
    id: 11,
    name: 'Hud',
    arabicName: 'هود',
    ayat: 123,
  },
  {
    id: 12,
    name: 'Yusuf',
    arabicName: 'يوسف',
    ayat: 111,
  },
  {
    id: 13,
    name: 'Ar-Ra’d',
    arabicName: 'الرعد',
    ayat: 43,
  },
  {
    id: 14,
    name: 'Ibrahim',
    arabicName: 'إبراهيم',
    ayat: 52,
  },
  {
    id: 15,
    name: 'Al-Hijr',
    arabicName: 'الحجر',
    ayat: 99,
  },
  {
    id: 16,
    name: 'An-Nahl',
    arabicName: 'النحل',
    ayat: 128,
  },
  {
    id: 17,
    name: 'Al-Isra',
    arabicName: 'الإسراء',
    ayat: 111,
  },
  {
    id: 18,
    name: 'Al-Kahf',
    arabicName: 'الكهف',
    ayat: 110,
  },
  {
    id: 19,
    name: 'Maryam',
    arabicName: 'مريم',
    ayat: 98,
  },
  {
    id: 20,
    name: 'Ta-Ha',
    arabicName: 'طه',
    ayat: 135,
  },
  {
    id: 21,
    name: 'Al-Anbiya',
    arabicName: 'الأنبياء',
    ayat: 112,
  },
  {
    id: 22,
    name: 'Al-Hajj',
    arabicName: 'الحج',
    ayat: 78,
  },
  {
    id: 23,
    name: 'Al-Muminun',
    arabicName: 'المؤمنون',
    ayat: 118,
  },
  {
    id: 24,
    name: 'An-Nur',
    arabicName: 'النور',
    ayat: 64,
  },
  {
    id: 25,
    name: 'Al-Furqan',
    arabicName: 'الفرقان',
    ayat: 77,
  },
  {
    id: 26,
    name: 'Ash-Shu’ara',
    arabicName: 'الشعراء',
    ayat: 227,
  },
  {
    id: 27,
    name: 'An-Naml',
    arabicName: 'النمل',
    ayat: 93,
  },
  {
    id: 28,
    name: 'Al-Qasas',
    arabicName: 'القصص',
    ayat: 88,
  },
  {
    id: 29,
    name: 'Al-Ankabut',
    arabicName: 'العنكبوت',
    ayat: 69,
  },
  {
    id: 30,
    name: 'Ar-Rum',
    arabicName: 'الروم',
    ayat: 60,
  },
  {
    id: 31,
    name: 'Luqman',
    arabicName: 'لقمان',
    ayat: 34,
  },
  {
    id: 32,
    name: 'As-Sajdah',
    arabicName: 'السجدة',
    ayat: 30,
  },
  {
    id: 33,
    name: 'Al-Ahzab',
    arabicName: 'الأحزاب',
    ayat: 73,
  },
  {
    id: 34,
    name: 'Saba',
    arabicName: 'سبأ',
    ayat: 54,
  },
  {
    id: 35,
    name: 'Fatir',
    arabicName: 'فاطر',
    ayat: 45,
  },
  {
    id: 36,
    name: 'Ya-Sin',
    arabicName: 'يس',
    ayat: 83,
  },
  {
    id: 37,
    name: 'As-Saffat',
    arabicName: 'الصافات',
    ayat: 182,
  },
  {
    id: 38,
    name: 'Sad',
    arabicName: 'الزخرف',
    ayat: 88,
  },
  {
    id: 39,
    name: 'Az-Zumar',
    arabicName: 'الزمر',
    ayat: 75,
  },
  {
    id: 40,
    name: 'Ghafir',
    arabicName: 'الغافر',
    ayat: 85,
  },
  {
    id: 41,
    name: 'Fussilat',
    arabicName: 'الفصلات',
    ayat: 54,
  },
  {
    id: 42,
    name: 'Ash-Shura',
    arabicName: 'الشورى',
    ayat: 53,
  },
  {
    id: 43,
    name: 'Az-Zukhruf',
    arabicName: 'الزخرف',
    ayat: 89,
  },
  {
    id: 44,
    name: 'Ad-Dukhan',
    arabicName: 'الدخان',
    ayat: 59,
  },
  {
    id: 45,
    name: 'Al-Jathiyah',
    arabicName: 'الجاثية',
    ayat: 37,
  },
  {
    id: 46,
    name: 'Al-Ahqaf',
    arabicName: 'الأحقاف',
    ayat: 35,
  },
  {
    id: 47,
    name: 'Muhammad',
    arabicName: 'محمد',
    ayat: 38,
  },
  {
    id: 48,
    name: 'Al-Fath',
    arabicName: 'الفتح',
    ayat: 29,
  },
  {
    id: 49,
    name: 'Al-Hujurat',
    arabicName: 'الحجرات',
    ayat: 18,
  },
  {
    id: 50,
    name: 'Qaf',
    arabicName: 'ق',
    ayat: 45,
  },
  {
    id: 51,
    name: 'Adh-Dhariyat',
    arabicName: 'الذاريات',
    ayat: 60,
  },
  {
    id: 52,
    name: 'At-Tur',
    arabicName: 'الطور',
    ayat: 49,
  },
  {
    id: 53,
    name: 'An-Najm',
    arabicName: 'النجم',
    ayat: 62,
  },
  {
    id: 54,
    name: 'Al-Qamar',
    arabicName: 'القمر',
    ayat: 55,
  },
  {
    id: 55,
    name: 'Ar-Rahman',
    arabicName: 'الرحمن',
    ayat: 78,
  },
  {
    id: 56,
    name: 'Al-Waqi’ah',
    arabicName: 'الواقعة',
    ayat: 96,
  },
  {
    id: 57,
    name: 'Al-Hadid',
    arabicName: 'الحديد',
    ayat: 29,
  },
  {
    id: 58,
    name: 'Al-Mujadilah',
    arabicName: 'المجادلة',
    ayat: 22,
  },
  {
    id: 59,
    name: 'Al-Hashr',
    arabicName: 'الحشر',
    ayat: 24,
  },
  {
    id: 60,
    name: 'Al-Mumtahanah',
    arabicName: 'الممتحنة',
    ayat: 13,
  },
  {
    id: 61,
    name: 'As-Saff',
    arabicName: 'الصف',
    ayat: 14,
  },
  {
    id: 62,
    name: 'Al-Jumuah',
    arabicName: 'الجمعة',
    ayat: 11,
  },
  {
    id: 63,
    name: 'Al-Munafiqun',
    arabicName: 'المنافقون',
    ayat: 11,
  },
  {
    id: 64,
    name: 'At-Taghabun',
    arabicName: 'التغابن',
    ayat: 18,
  },
  {
    id: 65,
    name: 'At-Talaq',
    arabicName: 'الطلاق',
    ayat: 12,
  },
  {
    id: 66,
    name: 'At-Tahrim',
    arabicName: 'التحريم',
    ayat: 12,
  },
  {
    id: 67,
    name: 'Al-Mulk',
    arabicName: 'الملك',
    ayat: 30,
  },
  {
    id: 68,
    name: 'Al-Qalam',
    arabicName: 'القلم',
    ayat: 52,
  },
  {
    id: 69,
    name: 'Al-Haqqah',
    arabicName: 'الحاقة',
    ayat: 52,
  },
  {
    id: 70,
    name: 'Al-Ma’arij',
    arabicName: 'المعارج',
    ayat: 44,
  },
  {
    id: 71,
    name: 'Nuh',
    arabicName: 'نوح',
    ayat: 28,
  },
  {
    id: 72,
    name: 'Al-Jinn',
    arabicName: 'الجن',
    ayat: 28,
  },
  {
    id: 73,
    name: 'Al-Muzzammil',
    arabicName: 'المزمل',
    ayat: 20,
  },
  {
    id: 74,
    name: 'Al-Muddaththir',
    arabicName: 'المدثر',
    ayat: 56,
  },
  {
    id: 75,
    name: 'Al-Qiyamah',
    arabicName: 'القيامة',
    ayat: 40,
  },
  {
    id: 76,
    name: 'Al-Insan',
    arabicName: 'الانسان',
    ayat: 31,
  },
  {
    id: 77,
    name: 'Al-Mursalat',
    arabicName: 'المرسلات',
    ayat: 50,
  },
  {
    id: 78,
    name: 'An-Naba',
    arabicName: 'النبأ',
    ayat: 40,
  },
  {
    id: 79,
    name: 'An-Naziat',
    arabicName: 'النذر',
    ayat: 46,
  },
  {
    id: 80,
    name: 'Abasa',
    arabicName: 'النصر',
    ayat: 42,
  },
  {
    id: 81,
    name: 'At-Takwir',
    arabicName: 'التكوير',
    ayat: 29,
  },
  {
    id: 82,
    name: 'Al-Infitar',
    arabicName: 'الإنفطار',
    ayat: 19,
  },
  {
    id: 83,
    name: 'Al-Mutaffifin',
    arabicName: 'المطففين',
    ayat: 36,
  },
  {
    id: 84,
    name: 'Al-Inshiqaq',
    arabicName: 'الإنشقاق',
    ayat: 25,
  },
  {
    id: 85,
    name: 'Al-Buruj',
    arabicName: 'البروج',
    ayat: 22,
  },
  {
    id: 86,
    name: 'At-Tariq',
    arabicName: 'الطارق',
    ayat: 17,
  },
  {
    id: 87,
    name: 'Al-Ala',
    arabicName: 'الأعلى',
    ayat: 19,
  },
  {
    id: 88,
    name: 'Al-Ghashiyah',
    arabicName: 'الغاشية',
    ayat: 26,
  },
  {
    id: 89,
    name: 'Al-Fajr',
    arabicName: 'الفجر',
    ayat: 30,
  },
  {
    id: 90,
    name: 'Al-Balad',
    arabicName: 'البلد',
    ayat: 20,
  },
  {
    id: 91,
    name: 'Ash-Shams',
    arabicName: 'الشمس',
    ayat: 15,
  },
  {
    id: 92,
    name: 'Al-Lail',
    arabicName: 'الليل',
    ayat: 21,
  },
  {
    id: 93,
    name: 'Ad-Duha',
    arabicName: 'الضحى',
    ayat: 11,
  },
  {
    id: 94,
    name: 'Al-Inshirah',
    arabicName: 'الإنشراح',
    ayat: 8,
  },
  {
    id: 95,
    name: 'At-Tin',
    arabicName: 'التين',
    ayat: 8,
  },
  {
    id: 96,
    name: 'Al-Alaq',
    arabicName: 'العلق',
    ayat: 19,
  },
  {
    id: 97,
    name: 'Al-Qadr',
    arabicName: 'القدر',
    ayat: 5,
  },
  {
    id: 98,
    name: 'Al-Bayyinah',
    arabicName: 'البينة',
    ayat: 8,
  },
  {
    id: 99,
    name: 'Az-Zalzalah',
    arabicName: 'الزلزلة',
    ayat: 8,
  },
  {
    id: 100,
    name: 'Al-Adiyat',
    arabicName: 'العاديات',
    ayat: 11,
  },
  {
    id: 101,
    name: 'Al-Qariah',
    arabicName: 'القارعة',
    ayat: 11,
  },
  {
    id: 102,
    name: 'At-Takathur',
    arabicName: 'التكاثر',
    ayat: 8,
  },
  {
    id: 103,
    name: 'Al-Asr',
    arabicName: 'العصر',
    ayat: 3,
  },
  {
    id: 104,
    name: 'Al-Humazah',
    arabicName: 'الهمزة',
    ayat: 9,
  },
  {
    id: 105,
    name: 'Al-Fil',
    arabicName: 'الفيل',
    ayat: 5,
  },
  {
    id: 106,
    name: 'Quraish',
    arabicName: 'قريش',
    ayat: 4,
  },
  {
    id: 107,
    name: 'Al-Maun',
    arabicName: 'المعان',
    ayat: 7,
  },
  {
    id: 108,
    name: 'Al-Kauther',
    arabicName: 'الكافرون',
    ayat: 3,
  },
  {
    id: 109,
    name: 'Al-Kafirun',
    arabicName: 'الكافرون',
    ayat: 6,
  },
  {
    id: 110,
    name: 'An-Nasr',
    arabicName: 'النصر',
    ayat: 3,
  },
  {
    id: 111,
    name: 'Al-Masad',
    arabicName: 'المسد',
    ayat: 5,
  },
  {
    id: 112,
    name: 'Al-Ikhlas',
    arabicName: 'الإخلاص',
    ayat: 4,
  },
  {
    id: 113,
    name: 'Al-Falaq',
    arabicName: 'الفلق',
    ayat: 5,
  },
  {
    id: 114,
    name: 'An-Nas',
    arabicName: 'الناس',
    ayat: 6,
  },
];

export const paths = [
  { params: { id: '1' } },
  { params: { id: '2' } },
  { params: { id: '3' } },
  { params: { id: '4' } },
  { params: { id: '5' } },
  { params: { id: '6' } },
  { params: { id: '7' } },
  { params: { id: '8' } },
  { params: { id: '9' } },
  { params: { id: '10' } },
  { params: { id: '11' } },
  { params: { id: '12' } },
  { params: { id: '13' } },
  { params: { id: '14' } },
  { params: { id: '15' } },
  { params: { id: '16' } },
  { params: { id: '17' } },
  { params: { id: '18' } },
  { params: { id: '19' } },
  { params: { id: '20' } },
  { params: { id: '21' } },
  { params: { id: '22' } },
  { params: { id: '23' } },
  { params: { id: '24' } },
  { params: { id: '25' } },
  { params: { id: '26' } },
  { params: { id: '27' } },
  { params: { id: '28' } },
  { params: { id: '29' } },
  { params: { id: '30' } },
  { params: { id: '31' } },
  { params: { id: '32' } },
  { params: { id: '33' } },
  { params: { id: '34' } },
  { params: { id: '35' } },
  { params: { id: '36' } },
  { params: { id: '37' } },
  { params: { id: '38' } },
  { params: { id: '39' } },
  { params: { id: '40' } },
  { params: { id: '41' } },
  { params: { id: '42' } },
  { params: { id: '43' } },
  { params: { id: '44' } },
  { params: { id: '45' } },
  { params: { id: '46' } },
  { params: { id: '47' } },
  { params: { id: '48' } },
  { params: { id: '49' } },
  { params: { id: '50' } },
  { params: { id: '51' } },
  { params: { id: '52' } },
  { params: { id: '53' } },
  { params: { id: '54' } },
  { params: { id: '55' } },
  { params: { id: '56' } },
  { params: { id: '57' } },
  { params: { id: '58' } },
  { params: { id: '59' } },
  { params: { id: '60' } },
  { params: { id: '61' } },
  { params: { id: '62' } },
  { params: { id: '63' } },
  { params: { id: '64' } },
  { params: { id: '65' } },
  { params: { id: '66' } },
  { params: { id: '67' } },
  { params: { id: '68' } },
  { params: { id: '69' } },
  { params: { id: '70' } },
  { params: { id: '71' } },
  { params: { id: '72' } },
  { params: { id: '73' } },
  { params: { id: '74' } },
  { params: { id: '75' } },
  { params: { id: '76' } },
  { params: { id: '77' } },
  { params: { id: '78' } },
  { params: { id: '79' } },
  { params: { id: '80' } },
  { params: { id: '81' } },
  { params: { id: '82' } },
  { params: { id: '83' } },
  { params: { id: '84' } },
  { params: { id: '85' } },
  { params: { id: '86' } },
  { params: { id: '87' } },
  { params: { id: '88' } },
  { params: { id: '89' } },
  { params: { id: '90' } },
  { params: { id: '91' } },
  { params: { id: '92' } },
  { params: { id: '93' } },
  { params: { id: '94' } },
  { params: { id: '95' } },
  { params: { id: '96' } },
  { params: { id: '97' } },
  { params: { id: '98' } },
  { params: { id: '99' } },
  { params: { id: '100' } },
  { params: { id: '101' } },
  { params: { id: '102' } },
  { params: { id: '103' } },
  { params: { id: '104' } },
  { params: { id: '105' } },
  { params: { id: '106' } },
  { params: { id: '107' } },
  { params: { id: '108' } },
  { params: { id: '109' } },
  { params: { id: '110' } },
  { params: { id: '111' } },
  { params: { id: '112' } },
  { params: { id: '113' } },
  { params: { id: '114' } },
];
